In [9]:
import numpy as np
np1 = np.array([1,2,3,4])
np1

array([1, 2, 3, 4])

#Matrix
##Create Matrix

In [10]:
Mat1=np.array([[1,2],[3,4]])
Mat1

array([[1, 2],
       [3, 4]])

In [11]:
Mat1.shape

(2, 2)

In [12]:
Mat1[0,1] = 57
Mat1

array([[ 1, 57],
       [ 3,  4]])

In [13]:
Mat2 = np.arange(0,10,1)
Mat2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
Mat3 = np.linspace(0,10,20)
Mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [15]:
Mat4 = np.random.rand(5,5)
Mat4

array([[0.39206766, 0.04452565, 0.40855623, 0.9544747 , 0.55787977],
       [0.89181971, 0.42678885, 0.88915064, 0.07201568, 0.17361115],
       [0.71446117, 0.87229207, 0.63931457, 0.2100878 , 0.13093108],
       [0.96637688, 0.54888354, 0.32910817, 0.28131884, 0.35178164],
       [0.37616742, 0.95215061, 0.56841403, 0.92994619, 0.57326684]])

In [16]:
Mat5 = np.random.randn(5,5)
Mat5

array([[ 0.037245  ,  1.10360001, -0.9259732 ,  0.13524229, -0.63791152],
       [ 1.28432248, -0.14441831,  0.76397363, -0.43501384, -0.14074945],
       [ 0.64335388, -0.07436203, -0.68422813,  1.11945674, -0.07344231],
       [-0.41713071,  1.07259863,  0.64968772, -0.61596937, -0.81729355],
       [-0.97289728,  0.09724746, -0.34462257, -1.45857058,  0.62613533]])

In [18]:
Mat5[0:3,:]

array([[ 0.037245  ,  1.10360001, -0.9259732 ,  0.13524229, -0.63791152],
       [ 1.28432248, -0.14441831,  0.76397363, -0.43501384, -0.14074945],
       [ 0.64335388, -0.07436203, -0.68422813,  1.11945674, -0.07344231]])